version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - 5672:5672
      - 15672:15672
  stats:
    image: mafia-stats
    build:
      context: ./
      dockerfile: stats.dockerfile
    ports:
      - 6669:6669
  server:
    image: mafia-server
    build:
      context: ./
      dockerfile: server.dockerfile
    ports:
      - 5050:5050
    depends_on:
      - rabbitmq
      - stats
