// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: protos/connection.proto

package mafia_connection

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MafiaService_RouteGame_FullMethodName = "/Mafia.Connection.MafiaService/RouteGame"
)

// MafiaServiceClient is the client API for MafiaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MafiaServiceClient interface {
	RouteGame(ctx context.Context, opts ...grpc.CallOption) (MafiaService_RouteGameClient, error)
}

type mafiaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMafiaServiceClient(cc grpc.ClientConnInterface) MafiaServiceClient {
	return &mafiaServiceClient{cc}
}

func (c *mafiaServiceClient) RouteGame(ctx context.Context, opts ...grpc.CallOption) (MafiaService_RouteGameClient, error) {
	stream, err := c.cc.NewStream(ctx, &MafiaService_ServiceDesc.Streams[0], MafiaService_RouteGame_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &mafiaServiceRouteGameClient{stream}
	return x, nil
}

type MafiaService_RouteGameClient interface {
	Send(*PlayerAction) error
	Recv() (*ServerAction, error)
	grpc.ClientStream
}

type mafiaServiceRouteGameClient struct {
	grpc.ClientStream
}

func (x *mafiaServiceRouteGameClient) Send(m *PlayerAction) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mafiaServiceRouteGameClient) Recv() (*ServerAction, error) {
	m := new(ServerAction)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MafiaServiceServer is the server API for MafiaService service.
// All implementations must embed UnimplementedMafiaServiceServer
// for forward compatibility
type MafiaServiceServer interface {
	RouteGame(MafiaService_RouteGameServer) error
	mustEmbedUnimplementedMafiaServiceServer()
}

// UnimplementedMafiaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMafiaServiceServer struct {
}

func (UnimplementedMafiaServiceServer) RouteGame(MafiaService_RouteGameServer) error {
	return status.Errorf(codes.Unimplemented, "method RouteGame not implemented")
}
func (UnimplementedMafiaServiceServer) mustEmbedUnimplementedMafiaServiceServer() {}

// UnsafeMafiaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MafiaServiceServer will
// result in compilation errors.
type UnsafeMafiaServiceServer interface {
	mustEmbedUnimplementedMafiaServiceServer()
}

func RegisterMafiaServiceServer(s grpc.ServiceRegistrar, srv MafiaServiceServer) {
	s.RegisterService(&MafiaService_ServiceDesc, srv)
}

func _MafiaService_RouteGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MafiaServiceServer).RouteGame(&mafiaServiceRouteGameServer{stream})
}

type MafiaService_RouteGameServer interface {
	Send(*ServerAction) error
	Recv() (*PlayerAction, error)
	grpc.ServerStream
}

type mafiaServiceRouteGameServer struct {
	grpc.ServerStream
}

func (x *mafiaServiceRouteGameServer) Send(m *ServerAction) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mafiaServiceRouteGameServer) Recv() (*PlayerAction, error) {
	m := new(PlayerAction)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MafiaService_ServiceDesc is the grpc.ServiceDesc for MafiaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MafiaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Mafia.Connection.MafiaService",
	HandlerType: (*MafiaServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RouteGame",
			Handler:       _MafiaService_RouteGame_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/connection.proto",
}
