// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	ID       string   `json:"id"`
	User     []*User  `json:"user"`
	Comments []string `json:"comments"`
}

type NewComment struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type User struct {
	Nickname string `json:"nickname"`
	IsWinner bool   `json:"isWinner"`
	Role     string `json:"role"`
}
